### ISSUE TITLE
Update to latest version: flutter_bluetooth_serial: ^0.2.2

### ISSUE THREAD

**Issue by sbis04** [sbis04/flutter_bluetooth#3]
Make the required changes to the project, for making it compatible with the latest version of the `flutter_bluetooth_serial: ^0.2.2` package.

**Comment by mannprerak2** [comment]
I tried to do this, but the flutter_bluetooth_serial ha completely revamped their API. It supports multiple devices now and each device has its own Bluetooth connection object.
The whole project may need to be written again.

**Comment by sbis04** [comment]
Updated to `flutter_bluetooth_serial: ^0.2.2` in PR: #6
