### ISSUE TITLE
Bluetooth -> BLE

### ISSUE THREAD

**Issue by GianfryPeres** [sbis04/flutter_bluetooth#7]
Hallo...
It's first time I've found Arduino's source without library...
That's what I need for some incompatible processor.
But... About Flutter BLE and ht-10 (or other processor)?
ArduinoBLE.h doesn't work with incompatible...
Can you help?
PLEASE
PLEASE

@}-,-'-----
Gianfranco

**Comment by sbis04** [comment]
Hey @GianfryPeres, I have used **HC-05** Bluetooth module for my project. This article contains a code for the **Arduino** as well: https://blog.codemagic.io/creating-iot-based-flutter-app/

Check it out and let me know if it helps.

**Comment by sbis04** [comment]
Assuming it to be solved. Closing this issue.

**Comment by GianfryPeres** [comment]
Thank you!!!



Da: "Souvik Biswas" notifications@github.com
A: "sbis04/flutter_bluetooth" flutter_bluetooth@noreply.github.com
Cc: "GianfryPeres" gianfry@abbici.org,"Mention" mention@noreply.github.com
Data: Fri, 24 Jul 2020 02:01:47 -0700
Oggetto: Re: [sbis04/flutter_bluetooth] Bluetooth -> BLE (#7)



Closed #7.
